/* Generated by Together */

package com.bos.actions;
//  java
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.bcop.arch.logger.Logger;
import com.bos.helper.ViewOnlineReportingHelper;

/**
 * This action class is used for the Main screen.<Br>
 */

public class ViewOnlineReportingAction extends BaseAction {

	static {
		logger =
			(Logger) Logger.getLogger(ViewOnlineReportingAction.class.getName());
	}

	public ActionForward processAction(
	ActionMapping mapping,
	ActionForm actionForm,
	HttpServletRequest request,
	HttpServletResponse response) {
        System.out.println("!!! Action Hit  -> "+this.getClass().getName());
		ActionForward actionForward=null;
		String forwardString = "error";
		String requestId = null;
        actionForward = mapping.findForward("success");
		//run XMLBuilder
        String selectedDate = request.getParameter("selectedDate");
        
        
        ViewOnlineReportingHelper helper = null;
        
        if(selectedDate != null && !selectedDate.equals("")) {
        	StringBuffer b = new StringBuffer(selectedDate);
        	StringBuffer s = b.insert(4,'-');
        	StringBuffer b2 = new StringBuffer(s.toString());
        	StringBuffer s2 = b2.insert(7,'-');
        	
        	helper = new ViewOnlineReportingHelper(s2.toString());
        } else {
        	Calendar calendar = Calendar.getInstance();
         	StringBuffer todaysDate = new StringBuffer(); 
         	todaysDate.append(calendar.get(Calendar.DAY_OF_MONTH));
         	todaysDate.append(calendar.get(Calendar.MONTH));
         	todaysDate.append(calendar.get(Calendar.YEAR));
         	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
         	Date d = new Date();
         	calendar = GregorianCalendar.getInstance();
         	calendar.setTime(d);
         	calendar.add(Calendar.DAY_OF_MONTH,-1);
         	d=calendar.getTime();
         	String dateString = sdf.format(d);
         	
        	helper = new ViewOnlineReportingHelper(dateString);
        }

        request.setAttribute(DOM, helper.getXMLDocument());

		return actionForward;
	}
}

